pipeline:

  build_10:
    image: node:10
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t app-$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:18.03.1-ce
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag app-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/ukvi-complaints:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/ukvi-complaints:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_ukvi-complaints_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-ukvi-complaints
    branch: master
    deploy_to: dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=ukvi-complaints-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_ukvi-complaints_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-ukvi-complaints
    branch: master
    deploy_to: preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=ukvi-complaints-preprod
    when:
      event: deployment
      environment: preprod

  trigger_deploy_to_ukvi-complaints_prod:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-ukvi-complaints
    branch: master
    deploy_to: prod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=ukvi-complaints
    when:
      event: deployment
      environment: prod
